Web_app3/Web_app3/Models/VozilaPoslovnice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using AutoServis.Models;

namespace AutoServis.Models
{
    public class VozilaPoslovnice
    {
        public int VozilaPoslovniceId { get; set; }
        [DataType(DataType.Date)]
        public DateTime DatumUvoza { get; set; }
        public Poslovnica Poslovnica { get; set; }
        public int PoslovnicaID { get; set; }
        public VoziloProdaja VoziloProdaja { get; set; }
        public int VoziloProdajaID { get; set; }

    }
}

Web_app3/Web_app3/Controllers/VozilaPoslovniceController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoServis.EF;
using AutoServis.Models;
using ReflectionIT.Mvc.Paging;
using Microsoft.AspNetCore.Routing;
using AutoServis.Helper;

namespace AutoServis.Controllers
{
    [Autorizacija(false, false, false, true)]
    public class VozilaPoslovniceController : Controller
    {
        private readonly MojContext _context;

        public VozilaPoslovniceController(MojContext context)
        {
            _context = context;
        }

        // GET: VozilaPoslovnice
        public async Task<IActionResult> Index(string search, int Page = 1, string sortExpression = "DatumUvoza")
        {
            var qry = _context.vozilaposlovnice.AsNoTracking()
                    .Include(x => x.Poslovnica)
                    .Include(p => p.VoziloProdaja)
                    .Include(s => s.VoziloProdaja.Model)
                    .Include(x => x.VoziloProdaja)
                    .Include(x => x.VoziloProdaja.Model.marka)
                    .AsQueryable();

            if (!string.IsNullOrWhiteSpace(search))
            {
                qry = qry.Where(x => x.DatumUvoza.Year.ToString() == search || x.DatumUvoza.Month.ToString() == search
                || x.Poslovnica.Naziv.Contains(search)
                || x.VoziloProdaja.Model.Naziv.Contains(search) || x.VoziloProdaja.Model.marka.Nazvi.Contains(search));
            }

            var model = await PagingList<VozilaPoslovnice>.CreateAsync(
                                 qry, 10, Page, sortExpression, "DatumUvoza");

            model.RouteValue = new RouteValueDictionary {
            { "filter", search}
            };

            return View(model);
        }
        // GET: VozilaPoslovnice/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vozilaPoslovnice = await _context.vozilaposlovnice
                .Include(v => v.Poslovnica)
                .Include(v => v.VoziloProdaja)
                .SingleOrDefaultAsync(m => m.VozilaPoslovniceId == id);
            if (vozilaPoslovnice == null)
            {
                return NotFound();
            }

            return View(vozilaPoslovnice);
        }

        // GET: VozilaPoslovnice/Create
        public IActionResult Create()
        {
            ViewData["PoslovnicaID"] = new SelectList(_context.poslovnica, "Id", "Naziv");
            ViewData["VoziloProdajaID"] = new SelectList(_context.voziloprodaja, "VoziloProdajaID", "SifraAutomobila");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VozilaPoslovniceId,DatumUvoza,PoslovnicaID,VoziloProdajaID")] VozilaPoslovnice vozilaPoslovnice)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vozilaPoslovnice);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PoslovnicaID"] = new SelectList(_context.poslovnica, "Id", "Naziv", vozilaPoslovnice.Poslovnica);
            ViewData["VoziloProdajaID"] = new SelectList(_context.voziloprodaja, "VoziloProdajaID", "SifraAutomobila", vozilaPoslovnice.VoziloProdaja);
            return View(vozilaPoslovnice);
        }

        // GET: VozilaPoslovnice/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vozilaPoslovnice = await _context.vozilaposlovnice.SingleOrDefaultAsync(m => m.VozilaPoslovniceId == id);
            if (vozilaPoslovnice == null)
            {
                return NotFound();
            }
            ViewData["PoslovnicaID"] = new SelectList(_context.poslovnica, "Id", "Naziv", vozilaPoslovnice.Poslovnica);
            ViewData["VoziloProdajaID"] = new SelectList(_context.voziloprodaja, "VoziloProdajaID", "SifraAutomobila", vozilaPoslovnice.VoziloProdaja);
            return View(vozilaPoslovnice);
        }

        // POST: VozilaPoslovnice/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VozilaPoslovniceId,DatumUvoza,PoslovnicaID,VoziloProdajaID")] VozilaPoslovnice vozilaPoslovnice)
        {
            if (id != vozilaPoslovnice.VozilaPoslovniceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vozilaPoslovnice);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VozilaPoslovniceExists(vozilaPoslovnice.VozilaPoslovniceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PoslovnicaID"] = new SelectList(_context.poslovnica, "Id", "Naziv", vozilaPoslovnice.PoslovnicaID);
            ViewData["VoziloProdajaID"] = new SelectList(_context.voziloprodaja, "VoziloProdajaID", "SifraAutomobila", vozilaPoslovnice.VoziloProdaja);
            return View(vozilaPoslovnice);
        }

        // GET: VozilaPoslovnice/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vozilaPoslovnice = await _context.vozilaposlovnice
                .Include(v => v.Poslovnica)
                .Include(v => v.VoziloProdaja)
                .SingleOrDefaultAsync(m => m.VozilaPoslovniceId == id);
            if (vozilaPoslovnice == null)
            {
                return NotFound();
            }

            return View(vozilaPoslovnice);
        }

        // POST: VozilaPoslovnice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vozilaPoslovnice = await _context.vozilaposlovnice.SingleOrDefaultAsync(m => m.VozilaPoslovniceId == id);
            _context.vozilaposlovnice.Remove(vozilaPoslovnice);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VozilaPoslovniceExists(int id)
        {
            return _context.vozilaposlovnice.Any(e => e.VozilaPoslovniceId == id);
        }
    }
}

Web_app3/Web_app3/Views/VozilaPoslovnice/Create.cshtml
@model AutoServis.Models.VozilaPoslovnice

<h4>Dodavanje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="VozilaPoslovnice" asp-area="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DatumUvoza" class="control-label">Datum uvoza</label>
                <input asp-for="DatumUvoza" class="form-control" />
                <span asp-validation-for="DatumUvoza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PoslovnicaID" class="control-label">Poslovnica</label>
                <select asp-for="PoslovnicaID" class ="form-control" asp-items="ViewBag.PoslovnicaID"></select>
            </div>
            <div class="form-group">
                <label asp-for="VoziloProdajaID" class="control-label"> Šifra automobila</label>
                <select asp-for="VoziloProdajaID" class ="form-control" asp-items="ViewBag.VoziloProdajaID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Sačuvaj" class="btn btn-primary" />
                <a asp-action="Index"class="btn btn-default">Nazad na listu</a>

            </div>
        </form>
    </div>
</div>

<div>
</div>

Web_app3/Web_app3/Views/VozilaPoslovnice/Delete.cshtml
@model AutoServis.Models.VozilaPoslovnice

<h3>Da li ste sigurni da želite obrisati ovaj zapis?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Datum uvoza
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatumUvoza)
        </dd>
        <dt>
           Poslovnica
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Poslovnica.Naziv)
        </dd>
        <dt>
           Vozilo(datum proizvodnje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VoziloProdaja.DatumProizvodnje)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-controller="VozilaPoslovnice" asp-area="">
        <input type="hidden" asp-for="VozilaPoslovniceId" />
        <input type="submit" value="Izbriši" class="btn btn-primary" /> |
        <a asp-action="Index" class="btn btn-default" >Nazad na listu</a>
    </form>
</div>

Web_app3/Web_app3/Views/VozilaPoslovnice/Edit.cshtml
@model AutoServis.Models.VozilaPoslovnice

<h2>Uređivanje</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="VozilaPoslovnice" asp-area="">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="VozilaPoslovniceId" />
            <div class="form-group">
                <label asp-for="DatumUvoza" class="control-label">Datum uvoza</label>
                <input asp-for="DatumUvoza" class="form-control" />
                <span asp-validation-for="DatumUvoza" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PoslovnicaID" class="control-label">Poslovnica</label>
                <select asp-for="PoslovnicaID" class="form-control" asp-items="ViewBag.PoslovnicaID" style="height:35px"></select>
                <span asp-validation-for="PoslovnicaID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VoziloProdajaID" class="control-label">Šifra automobila</label>
                <select asp-for="VoziloProdajaID" class="form-control" asp-items="ViewBag.VoziloProdajaID" style="height:35px"></select>
                <span asp-validation-for="VoziloProdajaID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sačuvaj" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-default">Nazad na listu</a>
            </div>
        </form>
    </div>
</div>

Web_app3/Web_app3/Views/VozilaPoslovnice/Find.cshtml
@model AutoServis.ViewModels.VozilaPoslovniceVM

<a asp-controller="VozilaPoslovnice"  asp-area="" asp-action="Index" class="btn btn-primary btn-sm">
    <span class="glyphicon glyphicon-arrow-left"></span>Nazad
</a>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover table-condenseds" style="box-shadow: 0 4px 8px rgba(0,0,0,.08)" >
        <thead>
            <tr>
                <th>
                    Datum uvoza
                </th>
                <th>
                    Poslovnica
                </th>
                <th>
                    Šifra automobila
                </th>
                <th>
                    Marka
                </th>
                <th>
                    Model
                </th>

                <th>Akcije</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.vp)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DatumUvoza)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Poslovnica.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VoziloProdaja.SifraAutomobila)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VoziloProdaja.Model.marka.Nazvi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VoziloProdaja.Model.Naziv)
                    </td>

                    <td>
                        <a asp-action="Edit" asp-route-id="@item.VozilaPoslovniceId" class="btn btn-primary btn-xs">Izmjeni</a> 
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Web_app3/Web_app3/Views/VozilaPoslovnice/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<AutoServis.Models.VozilaPoslovnice>
@using ReflectionIT.Mvc.Paging
@addTagHelper *, ReflectionIT.Mvc.Paging

<div class="table-responsive" style="margin-left:2%">
    <center><h2>Podaci o uvozu</h2></center>
    <div class="form-inline">
        <form method="get" class="form-inline">

            <input type="text" name="search" class="form-control" placeholder="Pretraga"
                   value="@Model.RouteValue["Filter"]" style="height:40px" />
            <button type="submit" class="btn btn-primary btn-sm">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Pretrazi
            </button>
            <br />
        </form>
    </div>
    <br />
    <br />
 
    <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>
                    @Html.SortableHeaderFor(model => model.DatumUvoza, this.Model)
                </th>
                <th>
                    @Html.SortableHeaderFor(model => model.Poslovnica, this.Model)
                </th>
                <th>
                    Šifra automobila
                </th>
                <th>
                    @Html.SortableHeaderFor(model => model.VoziloProdaja.Model.marka, this.Model)
                </th>
                <th>
                    @Html.SortableHeaderFor(model => model.VoziloProdaja.Model, this.Model)
                </th>

                <th>Akcija</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DatumUvoza)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Poslovnica.Naziv)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VoziloProdaja.SifraAutomobila)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VoziloProdaja.Model.marka.Nazvi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VoziloProdaja.Model.Naziv)
                    </td>

                    <td>
                        <a asp-action="Edit" asp-route-id="@item.VozilaPoslovniceId" class="btn btn-primary btn-xs">Izmjeni</a>
                        @*<a asp-action="Delete" asp-route-id="@item.VozilaPoslovniceId" class="btn btn-danger">Obrisi</a>*@
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<nav>
    @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
</nav>