Web_app3/Web_app3/Controllers/AutomobiliKlijentController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoServis.EF;
using AutoServis.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoServis.Models;
using ReflectionIT.Mvc.Paging;
using System.Collections.Generic;

namespace AutoServis.Controllers
{

    public class AutomobiliKlijentController : Controller
    {

        private MojContext _context;

        public AutomobiliKlijentController(MojContext context)
        {
            _context = context;
        }

    
        
        public async Task<IActionResult> Index(int ? ModelID, 
         int? MarkaID, int? TipVoziilaID, int? TransmisijaID, int? godina, int? page)
        {
            if ( MarkaID != null ||  TipVoziilaID != null || TransmisijaID != null || godina != null)
            {

                var vozila = from n in _context.voziloprodaja
                             where n.isDeleted==false
                             select n;
                
               
               
             
                if (MarkaID != null)
                {

                    page = 1;

                    vozila = vozila.Include(v => v.BrojVrata)
                .Include(v => v.Gorivo)
                .Include(v => v.Model)
                .Include(v => v.Oprema)
                .Include(v => v.TipVozila)
                .Include(v => v.Transmisija)
                .Include(v => v.Model.marka).Where(v => v.Model.marka.MarkaId == MarkaID);
                }
                if (ModelID >0)
                {
                    page = 1;


                    vozila = vozila.Include(v => v.BrojVrata)
                .Include(v => v.Gorivo)
                .Include(v => v.Model)
                .Include(v => v.Oprema)
                .Include(v => v.TipVozila)
                .Include(v => v.Transmisija)
                .Include(v => v.Model.marka).Where(v => v.Model.ModelId == ModelID);
                }
                if (TransmisijaID != null)
                {
                    page = 1;


                    vozila = vozila.Include(v => v.BrojVrata)
                .Include(v => v.Gorivo)
                .Include(v => v.Model)
                .Include(v => v.Oprema)
                .Include(v => v.TipVozila)
                .Include(v => v.Transmisija)
                .Include(v => v.Model.marka).Where(v => v.Transmisija.TransmisijaId == TransmisijaID);
                }

                if (TipVoziilaID != null)
                {
                    page = 1;


                    vozila = vozila.Include(v => v.BrojVrata)
                .Include(v => v.Gorivo)
                .Include(v => v.Model)
                .Include(v => v.Oprema)
                .Include(v => v.TipVozila)
                .Include(v => v.Transmisija)
                .Include(v => v.Model.marka).Where(v => v.TipVozila.TipVozilaId == TipVoziilaID);
                }

                if (godina != null)
                {
                    page = 1;

                    vozila = vozila.Include(v => v.BrojVrata)
                .Include(v => v.Gorivo)
                .Include(v => v.Model)
                .Include(v => v.Oprema)
                .Include(v => v.TipVozila)
                .Include(v => v.Transmisija)
                .Include(v => v.Model.marka).Where(v => v.DatumProizvodnje.Year == godina);
                }

                ViewData["BrojVrataID"] = new SelectList(_context.brojvrata, "BrojVrataId", "Naziv");
                ViewData["GorivoID"] = new SelectList(_context.gorivo, "GorivoId", "Naziv");
                ViewData["OpremaID"] = new SelectList(_context.oprema, "OpremaId", "Naziv");
                ViewData["TipVozilaID"] = new SelectList(_context.tipvozila, "TipVozilaId", "Naziv");
                ViewData["TransmisijaID"] = new SelectList(_context.transmisija, "TransmisijaId", "Naziv");

                List<Marka> listaMarke1 = new List<Marka>();
                listaMarke1 = _context.marka.ToList();
                List<VoziloProdaja> listaVozila1 = new List<VoziloProdaja>();
                listaVozila1 = _context.voziloprodaja.Include(x => x.Model).Include(x => x.Model.marka).ToList();
                List<Marka> listaKonačna1 = new List<Marka>();
                for (int i = 0; i < listaMarke1.Count; i++)
                {
                    for (int j = 0; j < listaVozila1.Count; j++)
                    {
                        if (listaVozila1[j].Model.MarkaID == listaMarke1[i].MarkaId)
                        {

                            Marka nepostoji = null;
                            nepostoji = listaKonačna1.Find(x => x.MarkaId == listaMarke1[i].MarkaId);
                            if (nepostoji == null)
                            {
                                listaKonačna1.Add(listaMarke1[i]);

                            }

                        }
                    }
                }
                ViewData["MarkaID"] = new SelectList(listaKonačna1, "MarkaId", "Nazvi");



                var auta = vozila;
                ViewData["brojAuta"] = auta.Count();
                return View("Find",auta);
            }
            ViewData["BrojVrataID"] = new SelectList(_context.brojvrata, "BrojVrataId", "Naziv");
            ViewData["GorivoID"] = new SelectList(_context.gorivo, "GorivoId", "Naziv");
            ViewData["OpremaID"] = new SelectList(_context.oprema, "OpremaId", "Naziv");
            ViewData["TipVozilaID"] = new SelectList(_context.tipvozila, "TipVozilaId", "Naziv");
            ViewData["TransmisijaID"] = new SelectList(_context.transmisija, "TransmisijaId", "Naziv");

            List<Marka> listaMarke = new List<Marka>();
            listaMarke = _context.marka.ToList();
            List<VoziloProdaja> listaVozila = new List<VoziloProdaja>();
            listaVozila = _context.voziloprodaja.Include(x=>x.Model).Include(x=>x.Model.marka).ToList();
            List<Marka> listaKonačna = new List<Marka>();
            for (int i = 0; i < listaMarke.Count; i++)
            {
                for (int j = 0; j < listaVozila.Count; j++)
                {
                    if (listaVozila[j].Model.MarkaID == listaMarke[i].MarkaId)
                    {

                        Marka nepostoji = null;
                        nepostoji = listaKonačna.Find(x => x.MarkaId == listaMarke[i].MarkaId);
                        if (nepostoji == null)
                        {
                            listaKonačna.Add(listaMarke[i]);

                        }

                    }
                }
            }
            
            ViewData["MarkaID"] = new SelectList(listaKonačna, "MarkaId", "Nazvi");


            int pageSize = 6;
            var item = _context.voziloprodaja.Include(x => x.Model).Include(x => x.Model.marka).Where(x=>x.isDeleted==false).AsNoTracking();
            var model =  AutomobiliPaging<VoziloProdaja>.Create(item, page ??1,pageSize);
            return  View("Index2",model);
            
        }



        public async Task<IActionResult> Details2(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            VoziloProdaja voziloProdaja = _context.voziloprodaja.Find(id);
            voziloProdaja.brojPregleda++;
            _context.SaveChanges();
            var slike = _context.slike.Where(s => s.VoziloID == id).ToList();
            var autoVM = new DetaljiVM();
            autoVM.Auta= _context.voziloprodaja.Include(v => v.BrojVrata)
                .Include(v => v.Gorivo)
                .Include(v => v.Model)
                .Include(v => v.Oprema)
                .Include(v => v.TipVozila)
                .Include(v => v.Transmisija)
                .Include(v => v.Model.marka).SingleOrDefault(v => v.VoziloProdajaID == id);
            autoVM.Slike = slike;
            return View(autoVM);

        }

        public JsonResult VratiModele(int? id)
        {
            List<Model> lista = new List<Model>();
           
            lista = _context.model.Where(x => x.MarkaID == id).ToList();
            var vozila = _context.voziloprodaja.ToList();
            List<Model> lista2 = new List<Model>();

         

            for (int i = 0; i < lista.Count; i++)
            {
                for (int j  = 0; j < vozila.Count; j++)
                {
                    if (vozila[j].ModelID == lista[i].ModelId) {
                        var ide = lista[i].ModelId;
                        Model nepostiji = null;
                         nepostiji = lista2.Find(x=>x.ModelId==ide);
                        if (nepostiji == null)
                        {
                            lista2.Add(lista[i]);

                        }
                    }
                }
            }
            var broj = lista2.Count();
            lista2.Insert(0, new Model { ModelId = 0, Naziv = "Svi modeli" });

            return Json(new SelectList(lista2, "ModelId", "Naziv"));
            

        }


     




    }
}

Web_app3/Web_app3/Views/AutomobiliKlijent/Details2.cshtml
@model AutoServis.ViewModels.DetaljiVM
@using AutoServis.Helper

<style>
    .row > .column {
        padding: 0 8px;
    }

    .row:after {
        content: "";
        display: table;
        clear: both;
    }


    .column {
        /*float: left;*/
        width: 25%;
    }


    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        padding-top: 100px;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: black;
    }


    .modal-content {
        position: relative;
        background-color: #fefefe;
        margin: auto;
        padding: 0;
        width: 55%;
        max-width: 1200px;
    }


    .close {
        color: white;
        position: absolute;
        top: 10px;
        right: 25px;
        font-size: 55px;
        font-weight: bold;
    }

        .close:hover {
            color: white;
            text-decoration: none;
            cursor: pointer;
        }


    .mySlides {
        display: none;
    }


    .prev,
    .next {
        cursor: pointer;
        position: absolute;
        top: 50%;
        width: auto;
        padding: 16px;
        color: white;
        margin-top: -50px;
        font-weight: bold;
        font-size: 35px;
        transition: 0.6s ease;
        border-radius: 0 3px 3px 0;
        user-select: none;
        -webkit-user-select: none;
    }


    .next {
        right: 0;
        border-radius: 3px 0 0 3px;
    }


        .prev:hover,
        .next:hover {
            background-color: rgba(211, 211, 211,0.8);
        }







    .active,
    .demo:hover {
        opacity: 1;
    }

    img.hover-shadow {
        transition: 0.3s;
    }

    .hover-shadow:hover {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    }

    .modalUpit {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0,0,0);
        background-color: rgba(0,0,0,0.4);
    }

    /*Modal Content/Box*/
    .modal-contentUpit {
        background-color: #fefefe;
        margin: 8% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 35%;
    }


    .closeUpit {
        color: #aaa;
        float: right;
        font-size: 40px;
        font-weight: bold;
    }

        .closeUpit:hover,
        .closeUpit:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }
</style>

@{
    Uposlenik username = Context.GetLogiraniKorisnik();
}
@if (username == null || username.VrstaUposlenikaId == 2)
{
    <div id="preloader">
        <div class="loader"></div>
    </div>
}

<div class="container-fluid" style="margin-left:20px ">
    <h2 style="margin-left:25px;">@Html.DisplayFor(model => model.Auta.Model.marka.Nazvi) @Html.DisplayFor(model => model.Auta.Model.Naziv) </h2>
    <h3 style="margin-left:25px;"><b>@Html.DisplayFor(model => model.Auta.Cijena) KM</b> <a id="myBtnUpit" class="btn btn-info btn-xs">Pošalji upit</a> </h3>
    <br />

    <div class="col-sm-6">
        <img src="@Html.DisplayFor(enes=>enes.Auta.Slika)" class="img-responsive" style="float:left; width:100%; margin-right:10px;" alt="Image" />


        @for (int i = 0; i < Model.Slike.Count; i++)
        {
            <div class="row" style="display:inline-block">
                <div class="column" style="height:70px;width:100px;  margin-top:5px; margin-left:7px; margin-right:8px;">
                    @{
                        var base64 = Convert.ToBase64String(Model.Slike[i].Slika);
                        var slikaurl = string.Format("data:image/gif;base64,{0}", base64);
                    }
                    <img src='@slikaurl' onclick="openModal();currentSlide(@i+1)" style="width:100%;" alt="" class="hover-shadow">
                </div>

            </div>
        }

    </div>

    <div class="col-sm-3" style="float:left;">

        <hr />

        <div style="background-color:lightgray; height:30px;">
            <div style="float:left;font-size:17px;">
                <b>Godina proizvodnje:</b>
            </div>
            <div style="float:right; font-size:17px;margin-right:40px;">
                @Html.DisplayFor(model => model.Auta.DatumProizvodnje.Year)

            </div>
        </div>
        <div style="height:30px;">
            <div style="float:left;font-size:17px;">
                <b>Kilometraža:</b>
            </div>
            <div style="float:right; font-size:17px;margin-right:40px;">
                @Html.DisplayFor(model => model.Auta.Kilometraza) km

            </div>
        </div>
        <div style="background-color:lightgray;  height:30px;">
            <div style="float:left;font-size:17px;">
                <b>Kubikaža:</b>
            </div>
            <div style="float:right; font-size:17px;margin-right:40px;">
                @Html.DisplayFor(model => model.Auta.Kubikaza) cca
            </div>
        </div>
        <div style="height:30px;">
            <div style="float:left;font-size:17px;">
                <b>Snaga motora:</b>
            </div>
            <div style="float:right; font-size:17px;margin-right:40px;">
                @Html.DisplayFor(model => model.Auta.SnagaMotora) KS/kW
            </div>
        </div>

        <div style="background-color:lightgray;height:30px;">
            <div style="float:left;font-size:17px;">
                <b> Broj vrata:</b>
            </div>
            <div style="float:right; font-size:17px;margin-right:40px;">
                @Html.DisplayFor(model => model.Auta.BrojVrata.Naziv)
            </div>
        </div>
        <div style="height:30px;">
            <div style="float:left;font-size:17px;">
                <b>Gorivo:</b>
            </div>
            <div style="float:right;font-size:17px;margin-right:40px;">
                @Html.DisplayFor(model => model.Auta.Gorivo.Naziv)
            </div>
        </div>


        <div style="background-color:lightgray;height:30px; ">
            <div style="float:left;font-size:17px;">
                <b>Tip vozila:</b>
            </div>
            <div style="float:right;font-size:17px;margin-right:40px;">
                @Html.DisplayFor(model => model.Auta.TipVozila.Naziv)
            </div>
        </div>
        <div style="height:30px;">
            <div style="float:left;font-size:17px;">
                <b>Transmisija:</b>
            </div>
            <div style="float:right; font-size:17px;margin-right:40px;">
                @Html.DisplayFor(model => model.Auta.Transmisija.Naziv)
            </div>
        </div>




        <div>
            <hr />
            <p style="font-size:15px; margin-bottom:0px;"><b>Dodatna oprema:</b></p>
            <p style="color:indianred; margin-left:35px; ">@Html.DisplayFor(model => model.Auta.Oprema.Opis)</p>


        </div>

    </div>

    <div id="myModal" class="modal">
        <span class="close" onclick="closeModal()">&times;</span>
        <div class="modal-content">

            @for (int i = 0; i < Model.Slike.Count; i++)
            {
                <div class="mySlides">
                    <div class="numbertext"></div>
                    @{
                        var base64 = Convert.ToBase64String(Model.Slike[i].Slika);
                        var slikaurl = string.Format("data:image/gif;base64,{0}", base64);
                    }
                    <img src="@slikaurl" style="width:100%">
                </div>
            }



            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>



        </div>
    </div>


    <div id="myModalUpit" class="modalUpit">
        <div class="modal-contentUpit" id="modal-content">
            <span class="closeUpit cursor">&times;</span>

            <div style="margin-left:10px;margin-top:50px;">
                <form id="formica" asp-action="Create" asp-controller="UpitiVozila" asp-area="">
                    <div class="card border-primary rounded-0">
                        <div class="card-header p-0">
                            <div class="bg-info text-white text-center py-2">
                                <h3><i class="fa fa-envelope"></i> Hvala na kontaktiranju, naš tim će se potruditi da što prije odgovori na Vaš upit.</h3>
                            </div>
                        </div>
                        <input name="id" value="@Model.Auta.VoziloProdajaID" hidden />

                        <div class="card-body p-3">
                            <!--Body-->
                            <div class="form-group">

                                <div class="input-group-prepend">
                                    <div style="font-size:25px;" class="input-group-text">
                                        <i class="fa fa-user text-info"></i>

                                    </div>
                                    <input type="text" class="form-control" id="ime" name="ime" oninvalid="this.setCustomValidity('Ime je obavezno!')"
                                           oninput="this.setCustomValidity('')" placeholder="Vaše ime i prezime" required />

                                </div>

                            </div>
                            <div class="form-group">

                                <div class="input-group-prepend">
                                    <div style="font-size:25px;" class="input-group-text"><i class="fa fa-envelope text-info"></i></div>
                                    <input type="email" class="form-control" id="email" name="email" oninvalid="this.setCustomValidity('Email je obavezan!')"
                                           oninput="this.setCustomValidity('')" placeholder="Vaš email" required>

                                </div>
                                <div id="error" class="alert alert-warning">
                                    <strong>Upozorenje!</strong> Molimo Vas da unesete validnu email adresu!
                                </div>
                            </div>

                            <div class="form-group">

                                <div class="input-group-prepend">
                                    <div style="font-size:25px;" class="input-group-text"><i class="fa fa-comment text-info"></i></div>
                                    <textarea class="form-control" id="poruka" name="text" oninvalid="this.setCustomValidity('Poruka je obavezna!')"
                                              oninput="this.setCustomValidity('')" placeholder="Vaša poruka" required></textarea>

                                </div>


                            </div>
                            <div class="text-center">
                                <input id="sub" type="submit" value="Pošalji" class="btn btn-info btn-block rounded-0 py-2">
                            </div>
                        </div>
                    </div>
                </form>
            </div>






        </div>
    </div>
</div>



<script>

    //$('input:submit').click(function () { this.disabled = true });
    $('input:submit').keypress(function (e) {
        if (e.which == 13) {
            this.disabled = true
        }
    }
    );

    $(document).ready(function () {

        $("#error").hide();
        $("#email").change(function () {

            function validateEmail($email) {
                var emailReg = /^([\w-\.]+@@([\w-]+\.)+[\w-]{2,6})?$/;
                return emailReg.test($email);
            }

            if (!validateEmail($("#email").val())) {

                $("#error").show();

                $("#email").addClass('error');



            }
            else {
                $("#error").hide();

                $("#email").removeClass('error');
            }
        });
    });





    function openModal() {
        document.getElementById('myModal').style.display = "block";
    }


    function closeModal() {
        document.getElementById('myModal').style.display = "none";
    }

    var slideIndex = 1;
    showSlides(slideIndex);


    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSlide(n) {
        showSlides(slideIndex = n);
    }

    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        if (n > slides.length) { slideIndex = 1 }
        if (n < 1) { slideIndex = slides.length }
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }

        slides[slideIndex - 1].style.display = "block";


    }

    // ModalUpit
    var modalUpit = document.getElementById('myModalUpit');

    // Get the button that opens the modal
    var btnUpit = document.getElementById("myBtnUpit");

    // Get the <span> element that closes the modal
    var spanUpit = document.getElementsByClassName("closeUpit")[0];

    // When the user clicks on the button, open the modal
    btnUpit.onclick = function () {
        modalUpit.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    spanUpit.onclick = function () {
        modalUpit.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modalUpit) {
            modalUpit.style.display = "none";
        }
    }


    //$('#myModalUpit').on('show.bs.modal', function () {
    //    $(this).find('.modal-body').css({
    //        'max-height': '100%'
    //    });
</script>

Web_app3/Web_app3/Views/AutomobiliKlijent/Find.cshtml
@model IEnumerable<AutoServis.Models.VoziloProdaja>
@using AutoServis.Helper

@{
    Uposlenik username = Context.GetLogiraniKorisnik();
}
@if (username == null || username.VrstaUposlenikaId == 2)
{
    <div id="preloader">
        <div class="loader"></div>
    </div>
}

@if (Model.Count() == 0)
{<center><h2>  Katalog vozila - Pretraga ( Nije pronađeno niti jedno traženo vozilo.) </h2></center>}

@if (Model.Count() > 0)
{<center><h2 style="position:center">Katalog vozila - Pretraga ( @ViewBag.brojAuta rezultata)</h2></center>}




<div class="container-fluid" style="margin-top:50px;">


    <div class="col-lg-8" style="display:inline-block;">
        @foreach (var item in Model)
        {


            <div class="col-lg-4" style="display:inline-block">
                <div class="panel panel-primary">
                    <div class="panel-heading"> @Html.DisplayFor(modelItem => item.Model.marka.Nazvi)  @Html.DisplayFor(modelItem => item.Model.Naziv)      Godina @Html.DisplayFor(modelItem => item.DatumProizvodnje.Year)</div>
                    <div class="panel-body"><img src="@Html.DisplayFor(modelItem=>item.Slika)" class="img-responsive" alt="Image"></div>
                    <div class="panel-footer"> <a asp-action="Details2" asp-controller="AutomobiliKlijent" asp-area="" asp-route-id="@item.VoziloProdajaID" class="btn btn-default btn-lg btn-block">Detalji</a> </div>
                </div>
            </div>




        }
    
        <div class="col-lg-2" style="float:right;margin-bottom:5px;">
           
        </div>
    </div>

    <div id="forma" class="col-sm-3" style="float:left;">
        <form method="get" asp-controller="AutomobiliKlijent" asp-action="Index" asp-area="">
            <div class="form-group">
                <select id="marka" class="form-control" name="MarkaID" style="height:40px;" asp-items="ViewBag.MarkaID">
                    <option value="">Marka</option>
                </select>
            </div>

            <div class="form-group">
                <select class="form-control" id="model" name="ModelID" style="height:40px;display:none" asp-items='@new SelectList("ModelId","Naziv")'><option value="">Tip vozila</option></select>
            </div>
            <div class="form-group">

                <select class="form-control" name="TipVoziilaID" style="height:40px" asp-items="ViewBag.TipVozilaID">
                    <option value="">Tip vozila</option>
                </select>
            </div>

            <div class="form-group">

                <select class="form-control" name="TransmisijaID" style="height:40px" asp-items="ViewBag.TransmisijaID">
                    <option value="">Transmisija</option>
                </select>
            </div>

            <div class="form-group">
                <input class="form-control" placeholder="Godina proizvodnje" type="text" name="godina" />
            </div>

            <div class="form-group">
                <button type="submit" style="width:100%" class="btn btn-primary">Pretraži</button>
            </div>
        </form>
    </div>





</div>










<script>
    $(function () {



        $("#marka").change(function () {
            var id = $(this).children(":selected").attr("value");
            if (id != "") {
                $.getJSON("/AutomobiliKlijent/VratiModele?id=" + id, function (rez) {
                    var items = '';
                    $("#model").empty();
                    $.each(rez, function (i, red) {
                        items += "<option value='" + red.value + "'>" + red.text + "</option>"

                    });
                    $("#model").html(items);
                });
                var model = document.getElementById("model");
                model.style.display = "block";



            }
            else {
                var model = document.getElementById("model");
                model.style.display = "none";

            }
        });
    });
</script>

Web_app3/Web_app3/Views/AutomobiliKlijent/Index2.cshtml
@model AutomobiliPaging<AutoServis.Models.VoziloProdaja>
@using AutoServis.Helper


@{
    Uposlenik username = Context.GetLogiraniKorisnik();
}
@if (username == null || username.VrstaUposlenikaId == 2)
{
    <div id="preloader">
        <div class="loader"></div>
    </div>
}

<div class="container-fluid" style="margin-top:50px;">


    <div class="col-lg-8" style="display:inline-block;">
        @foreach (var item in Model)
        {


            <div class="col-lg-4" style="display:inline-block">
                <div class="panel panel-primary">
                    <div class="panel-heading"> @Html.DisplayFor(modelItem => item.Model.marka.Nazvi)  @Html.DisplayFor(modelItem => item.Model.Naziv)      Godina @Html.DisplayFor(modelItem => item.DatumProizvodnje.Year)</div>
                    <div class="panel-body"><center><img src="@Html.DisplayFor(modelItem=>item.Slika)" class="img-responsive" style="height:150px" alt="Image"></center></div>
                    <div class="panel-footer"> <a asp-action="Details2" asp-controller="AutomobiliKlijent" asp-route-id="@item.VoziloProdajaID" asp-area="" class="btn btn-default btn-lg btn-block">Detalji vozila</a> </div>
                </div>
            </div>




        }
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <div class="col-lg-2" style="float:right;margin-bottom:5px;">
            <a asp-action="Index" asp-controller="AutomobiliKlijent" asp-area=""
               asp-route-page="@(Model.TrenutnaStranica - 1)" title="Nazad"
               class="btn btn-default @prevDisabled">
                <span class="glyphicon glyphicon-arrow-left"></span>
            </a>
            <a asp-action="Index" asp-controller="AutomobiliKlijent" asp-area="" title="Naprijed"
               asp-route-page="@(Model.TrenutnaStranica + 1)"
               class="btn btn-default @nextDisabled">
                <span class="glyphicon glyphicon-arrow-right"></span>
            </a>
        </div>
    </div>

    <div id="forma" class="col-sm-3" style="float:left;">
        <form method="get" asp-controller="AutomobiliKlijent" asp-action="Index">
            <div class="form-group">
                <select id="marka" class="form-control" name="MarkaID" style="height:40px;" asp-items="ViewBag.MarkaID">
                    <option value="">Marka</option>
                </select>
            </div>

            <div class="form-group">
                <select class="form-control" id="model" name="ModelID" style="height:40px;display:none" asp-items='@new SelectList("ModelId","Naziv")'><option value="">Svi modeli</option></select>
            </div>
            <div class="form-group">

                <select class="form-control" name="TipVoziilaID" style="height:40px" asp-items="ViewBag.TipVozilaID">
                    <option value="">Tip vozila</option>
                </select>
            </div>

            <div class="form-group">

                <select class="form-control" name="TransmisijaID" style="height:40px" asp-items="ViewBag.TransmisijaID">
                    <option value="">Transmisija</option>
                </select>
            </div>

            <div class="form-group">
                <input class="form-control" placeholder="Godina proizvodnje" type="text" name="godina" />
            </div>

            <div class="form-group">
                <button type="submit" style="width:100%" class="btn btn-primary">Pretraži</button>
            </div>
        </form>
    </div>





</div>


<script>
    $(function () {



        $("#marka").change(function () {
            var id = $(this).children(":selected").attr("value");
            if (id != "") {
                $.getJSON("/AutomobiliKlijent/VratiModele?id=" + id, function (rez) {
                    var items = '';
                    $("#model").empty();
                    $.each(rez, function (i, red) {
                        items += "<option value='" + red.value + "'>" + red.text + "</option>"

                    });
                    $("#model").html(items);
                });
                var model = document.getElementById("model");
                model.style.display = "block";



            }
            else {
                var model = document.getElementById("model");
                model.style.display = "none";

            }
        });
    });
</script>