Web_app3/Web_app3/Controllers/NarudzbaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoServis.EF;
using AutoServis.Helper;
using AutoServis.Hubs;
using AutoServis.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;

namespace AutoServis.Controllers
{

    public class NarudzbaController : Controller
    {
        private readonly MojContext _context;
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;
        private IHubContext<ReportsPublisher> _hubContext;
        public NarudzbaController(MojContext context,IOrderRepository orderRepository,ShoppingCart shoppingCart,IHubContext<ReportsPublisher> hubContext)
        {
            _context = context;
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
            _hubContext = hubContext;
        }

        public IActionResult Checkout()
        {
            IEnumerable<ShoppingCartItem> items = _shoppingCart.GetShoppingCartItems();
            var total = _shoppingCart.GetShoppingCartTotal();
            ViewBag.Items = items;
            ViewBag.Total = total;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Vasa korpa je prazna, dodajte dijelove prvo");
            }
            if (ModelState.IsValid)
            {
                var ukupno = _shoppingCart.GetShoppingCartTotal();
                if (ukupno <= 100)
                {
                    ukupno += 10;
                }
                if (ukupno > 200)
                {
                    ukupno = ukupno * 0.9;
                }
                order.Ukupno = ukupno;
                order.Zavrsena = false;
                Klijent klijent = null;
                var pretraga = _context.osoba.SingleOrDefault(x => x.Ime == order.Ime && x.Prezime == order.Prezime);
                if (pretraga != null) { klijent= _context.klijent.SingleOrDefault(x => x.OsobaId == pretraga.Id); }
                
                var grad = _context.grad.Where(g => g.Naziv == order.Grad).SingleOrDefault();
                if (grad == null)
                {
                    Grad novi = new Grad
                    {
                        Naziv = order.Grad
                    };
                    _context.grad.Add(novi);
                    _context.SaveChanges();
                }
                if (pretraga == null)
                {
                    var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
                    var stringChars = new char[8];
                    var random = new Random();

                    for (int i = 0; i < stringChars.Length; i++)
                    {
                        stringChars[i] = chars[random.Next(chars.Length)];
                    }

                    var finalString = new String(stringChars);
                    Osoba nova = new Osoba
                    {
                        Ime = order.Ime,
                        Prezime = order.Prezime,
                        Adresa = order.Adresa,
                        KorisnickoIme = finalString,
                        Lozinka = "",
                        Telefon = order.BrojTelefona,
                        Grad = _context.grad.Where(g => g.Naziv == order.Grad).SingleOrDefault()
                    };
                    _context.osoba.Add(nova);
                    var Klijent = new Klijent
                    {
                        DatumRegistracije = order.DatumNarudzbe,
                        BrojNarudzbi = 1,
                        OsobaId = nova.Id
                    };
                    _context.klijent.Add(Klijent);
                    _orderRepository.CreateOrder(order);
                    _shoppingCart.ClearCart();
                    _context.SaveChanges();
                    //_hubContext.Clients.All.InvokeAsync("displayNotification","");
                    _hubContext.Clients.All.SendAsync("displayNotification", "");
                }
                else
                {
                    _orderRepository.CreateOrder(order);
                    _shoppingCart.ClearCart();
                    if (klijent != null) {
                        klijent.BrojNarudzbi++;
                        _context.klijent.Update(klijent);
                    }
                    _context.SaveChanges();
                    _hubContext.Clients.All.SendAsync("displayNotification", "");
                }
                return RedirectToAction("CheckoutComplete");
            }
            return View(order);
        }
        public IActionResult CheckoutComplete()
        {
            //_hubContext.Clients.All.SendAsync("displayNotification", "");
            ViewBag.CheckoutCompleteMessage = "Hvala Vam na Vasoj narudzbi !";
            return View();
        }
    }
}

Web_app3/Web_app3/Views/Narudzba/Checkout.cshtml
@model Order

@using AutoServis.Helper

@{
    Uposlenik username = Context.GetLogiraniKorisnik();
}
@if (username == null || username.VrstaUposlenikaId == 2)
{
    <div id="preloader">
        <div class="loader"></div>
    </div>
}

@{ var sPopustom = ViewBag.Total * 0.9;
    var sPostarinom = ViewBag.Total + 10;
}
<h3 style="margin-left:20%">Dijeli vas jos jedan korak do kupovine dijelova.</h3>
<hr />
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-4" style="box-shadow: 0 4px 8px rgba(0,0,0,.08)">
        <form asp-action="Checkout" asp-controller="Narudzba" asp-area="" method="post" class="form-horizontal" role="form">
            <div class="form-group">
                <label asp-for="Ime" class="col-md-2 control-label"></label>
                <div class="col-md-7">
                    <input asp-for="Ime" required
                           oninvalid="this.setCustomValidity('Ime je obavezno!')"
                           oninput="this.setCustomValidity('')" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Prezime" class="col-md-2 control-label"></label>
                <div class="col-md-7">
                    <input asp-for="Prezime" required
                           oninvalid="this.setCustomValidity('Prezime je obavezno!')"
                           oninput="this.setCustomValidity('')" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Adresa" class="col-md-2 control-label"></label>
                <div class="col-md-7">
                    <input asp-for="Adresa" required
                           oninvalid="this.setCustomValidity('Adresa je obavezna!')"
                           oninput="this.setCustomValidity('')" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="ZipCode" class="col-md-2 control-label"></label>
                <div class="col-md-7">
                    <input asp-for="ZipCode" required
                           oninvalid="this.setCustomValidity('Zip code je obavezan!')"
                           oninput="this.setCustomValidity('')" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Grad" class="col-md-2 control-label"></label>
                <div class="col-md-7">
                    <input asp-for="Grad" required
                           oninvalid="this.setCustomValidity('Naziv grada je obavezan!')"
                           oninput="this.setCustomValidity('')" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Drzava" class="col-md-2 control-label"></label>
                <div class="col-md-7">
                    <input asp-for="Drzava" required
                           oninvalid="this.setCustomValidity('Naziv države je obavezan!')"
                           oninput="this.setCustomValidity('')" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Broj telefona</label>
                <div class="col-md-7">
                    <input asp-for="BrojTelefona" type="tel" required placeholder="3876xxxxxxx"
                           oninvalid="this.setCustomValidity('Telefon je obavezan!')"
                           oninput="this.setCustomValidity('')" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="col-md-2 control-label"></label>
                <div class="col-md-7">
                    <input asp-for="Email" type="email" required
                           oninvalid="this.setCustomValidity('Mail je obavezan!')"
                           oninput="this.setCustomValidity('')" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <div class="btn-group col-md-offset-2 col-md-8">
                    <input class="btn btn-primary" type="submit" value="Naruci" />
                </div>
            </div>

        </form>
    </div>
    <div class="col-md-4" style="box-shadow: 0 4px 8px rgba(0,0,0,.08)">
        <h3>Sadržaj korpe : </h3>
        <table class="table table-responsive">
            <colgroup>
                <col class="col-md-4">
                <col class="col-md-4">
                <col class="col-md-4">
            </colgroup>
            <thead>
                <tr>
                    <th>
                        Naziv
                    </th>
                    <th>
                        Količina
                    </th>
                    <th>
                        Cijena
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (ViewBag.Items != null)
                {@foreach (var item in ViewBag.Items)
                    {
                        <tr>
                            <td>
                                <h3>@item.Dio.Naziv</h3>  <small>@item.Dio.model.marka.Nazvi @item.Dio.model.Naziv </small>
                            </td>
                            <td>@item.Amount</td>
                            <td>
                                @(item.Amount * item.Dio.Cijena)KM
                            </td>
                        </tr>
                    }}

                @if (ViewBag.Total <= 100 && ViewBag.Items.Count != 0)
                {
                    <tr class="active">
                        <td colspan="2">Poštarina</td>
                        <td>10KM</td>
                    </tr>
                }
                <tr class="active" style="border-top:solid">

                    <td>Ukupno : </td>
                    <td colspan="2">
                        @if (ViewBag.Total <= 100 && ViewBag.Items.Count != 0)
                        {
                            @sPostarinom
                        }
                        else if (ViewBag.Total > 200)
                        {@sPopustom}
                    else
                    {@ViewBag.Total}KM
                    </td>
                </tr>
                <tr>
                    <td>
                        <ul>
                            <li>
                                <small><i class="glyphicon glyphicon-info-sign"></i></small>
                            </li>
                            <li>
                                <small><br />Na iznos od preko 200 KM ostvarujete popust od 10%.</small>
                            </li>
                            <li>
                                <small>Poštarina prema svim gradovima iznosi 10 KM, a za narudžbe preko 100 KM je besplatna.</small>
                            </li>
                        </ul>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<script>

</script>

Web_app3/Web_app3/Views/Narudzba/CheckoutComplete.cshtml
<h1>
    @ViewBag.CheckoutCompleteMessage
</h1>

<script>
    $(document).ready(function () {
        setTimeout(function () {
            window.location.replace('/Home/Index');
        }, 3000);
    })
</script>